### ISSUE TITLE
Critical - Cannot apply for a position~ Pre-App page seems unresponsive

### ISSUE THREAD

**Issue by transystems** [TransystemsLLC/ContactApp-4.6.1#2]
http://transystemsllc.com/#/apply/pre-app
Severity:Critical
If you complete the Pre-App fields as required, the buttons turn green indicating you are good to proceed. However, neither button is working. I have tried multiple browsers.

![2017-04-24 10_52_18-photos](https://cloud.githubusercontent.com/assets/16327097/25348647/22779e2a-28dc-11e7-8682-28ba3e9ba6a4.png)

**Comment by TomasPDL** [comment]
After digging around a bit more, I was able to discover that the issue with not being able to start an application is actually an error with the pre-app trying to connect to your email server.
We'll need some information on how your emails are routed as well as any credentials associated with those services.

Good news is solving this issue with the email server will most likely help us solve the password recovery issue as well.

While we look into this, we can kill two birds with one stone and look into the Facebook authentication issues as well if we are able to get the credentials to your Facebook developers account.

Image attached for reference showing how we know what's going on.
![chrome_2017-04-24_15-51-09](https://cloud.githubusercontent.com/assets/22530898/25362490/fb1053ea-2908-11e7-9e3d-faf823349e5e.png)

**Comment by transystems** [comment]
Tomas,
Can you see the credentials, IP or mail server, or other that would indicate how it was setup?

That will help me know where to look
Thanks

**Comment by TomasPDL** [comment]
Well, it would appear that you guys have an Auth0 account set up. If we could get access to that we can take a stab at the whitelist.

Also you guys should have a Facebook developers account.

Other than that, still digging through the code to see if it references what email service you guys are using.
![devenv_2017-04-24_17-51-31](https://cloud.githubusercontent.com/assets/22530898/25364367/d3ee3a3a-2916-11e7-91ef-5f6370f34730.png)

**Comment by transystems** [comment]
I found the account information that Devin used for Auth0. I as able to whitelist the new site. It is working as expected now.

**Comment by transystems** [comment]
Closed wrong item

**Comment by transystems** [comment]
Thomas,
I see there is a mail.cs file in the un-compiled version. I see there are two references to transystemsllc.net. Of course the new URL is transystemsllc.com

I do not know how to make compile, and post. I am afraid I would wipe out the site. All of the methods we use are different.

Please help…

Dan

**Comment by TomasPDL** [comment]
I went ahead and changed those, but the issue still persists.
The credentials must be different for mail.transystemsllc.com.

Here is a separate file which handles the login credentials, I need you to verify or correct this information so I can update this file and see if it works.

![devenv_2017-04-24_19-49-40](https://cloud.githubusercontent.com/assets/22530898/25367148/bf278a4a-2928-11e7-8cd9-4a88225df459.png)

**Comment by transystems** [comment]
I will give this a whirl. Devin set these up for us.

Dan

**Comment by TomasPDL** [comment]
Have you been able to find updated credentials or use these credentials to update the mail server?

**Comment by transystems** [comment]
Still working on it
Dan

**Comment by transystems** [comment]
Tomas, all email issues have been resolved. However, the next page does not allow account create an progress to next page. 

Have you had any headway?

**Comment by TomasPDL** [comment]
Huh, that was an issue we already fixed prior to going live. I'll have to take a look in the code and see if perhaps there were any reversions to the changes we made, hopefully it shouldn't be too much of an issue.

**Comment by transystems** [comment]
Thanks Tomas.
What did you do to fix it? Perhaps I could figure it out so we can get our backlog of employee applications started?

Thanks
Dan

**Comment by transystems** [comment]
Closing - this page is working, technically. The failed page is the next step in the process.
